### ISSUE TITLE
Implement designer login for security

### ISSUE THREAD

**Issue by anjgarong** [SiliconValleyInsight/fgi-catalog-ios#10]
- database tables
- verification (user authentication)
- tracking (in the future)

**Comment by stefsy** [comment]
For control purposes, designers would like to be able to have an assigned `username:password` to use before logging in to the application. No need for registration page, as long as someone can CRUD it on the admin interface. 

Designers would like to be able to track every time a quotation is emailed. Data to be tracked: username, time, list of email address sent to, email content

**Comment by ray-dino** [comment]
Django comes with a built-in users and authentication model. We can create accounts and assign permissions for each designer.

I'll go ahead and create a table to track quotations based on your description. But how do we track quotations? Should I create an API interface to allow the creation of quotation history as well?

**Comment by ray-dino** [comment]
https://github.com/SiliconValleyInsight/fgi-catalog-web/pull/31

I created a Quotation model and an admin page for CRUD. Should be ready after the next deployment.
