### ISSUE TITLE
Change layout/details in Product page: 1 name = 5 thumbnails

### ISSUE THREAD

**Issue by anjgarong** [SiliconValleyInsight/fgi-catalog-ios#12]

**Comment by stefsy** [comment]
Designers requested that they have the ability to upload up to 5 thumbnails at a time, instead of current 3 at a time

**Comment by ray-dino** [comment]
I've added extra thumbnails (total of 5 now) to the products db table. I also updated the product csv loader to consider the new thumbnail fields. This is reflected in the API responses.

I believe the change has been deployed. Assigning to @vinogradnaya now. 

cc @stefsy @anjgarong

**Comment by vinogradnaya** [comment]
fixed in build 1.13
