### ISSUE TITLE
FGI_iOS-021 bug: text fields at the lower half of the screen gets hidden

### ISSUE THREAD

**Issue by anjgarong** [SiliconValleyInsight/fgi-catalog-ios#13]
Screen: Project Area

Description:
When the text to be edited (either category name or price) is located at the lower half of the screen, it gets hidden because it is covered by the keyboard. As a result, the user cannot see what he/she is typing.

Expected Behavior:
The screen moves up when the keyboard is shown so the text fields to be edited is still seen.

Reference Screenshots:
![image](https://cloud.githubusercontent.com/assets/2359553/6990200/fb9d4c38-da99-11e4-9c75-2b2d0ce472fc.jpg)
![image](https://cloud.githubusercontent.com/assets/2359553/6990201/fc20cda6-da99-11e4-9c0a-a7c8f2d85c53.jpg)

Based on the screenshots, if you try to edit anything under the CHAIRS category, that text field that you want to edit will be hidden.

**Comment by vinogradnaya** [comment]
fixed build 1.13
