### ISSUE TITLE
FGI_iOS-026 bug: images dont appear in web/mobile browsers

### ISSUE THREAD

**Issue by anjgarong** [SiliconValleyInsight/fgi-catalog-ios#15]
Screen (outside app): Email sites in web/mobile browsers

Description:
• The images don't appear in web/mobile browsers. It only appears in desktop/mobile email client apps.

Expected Behavior:
• The images should be shown in both web/mobile browsers and desktop/mobile email client apps.

Screenshot of Mobile Browser (shows the same in web browser):
![image](https://cloud.githubusercontent.com/assets/2359553/6990546/b72b9e7c-daa0-11e4-9fda-8af0660ad3e0.jpg)

Screenshot of Mobile Email Client App (shows the same in desktop email client app):
![image](https://cloud.githubusercontent.com/assets/2359553/6990557/f87df1e0-daa0-11e4-95c0-87819298cba8.jpg)

**Comment by vinogradnaya** [comment]
fixed in build 1.13

**Comment by anjgarong** [comment]
checked in build 1.15

HTML code is shown in browsers. It says that the message is clipped but when you view the message, the pictures are not shown.

![screen shot 2015-04-09 at 9 13 43 am](https://cloud.githubusercontent.com/assets/2359553/7058949/41d5e048-de9b-11e4-961b-5e6a62865102.png)
![screen shot 2015-04-09 at 9 14 00 am](https://cloud.githubusercontent.com/assets/2359553/7058952/4ac08e60-de9b-11e4-90ed-6ddda526809a.png)
![screen shot 2015-04-09 at 9 14 17 am](https://cloud.githubusercontent.com/assets/2359553/7058953/5221d466-de9b-11e4-867d-00cb375544dd.png)

Looks fine in mail client apps (mobile and desktop).

Will forward the email to @stefsy and @vinogradnaya for reference.

**Comment by vinogradnaya** [comment]
Now it is definitely fixed. Tested in mobile / desktop browsers and mobile mail app. Please see build #1.16 and email sent from app.
