### ISSUE TITLE
Fix app orientation to landscape only

### ISSUE THREAD

**Issue by stefsy** [SiliconValleyInsight/fgi-catalog-ios#16]
In portrait mode, the menu bar is not seen. No indication that it ought to be in landscape mode.

Even if held in portrait orientation, the app must always be fixed in landscape mode so that all details are visible.

**Comment by vinogradnaya** [comment]
In portrait mode if you swipe from the left - the menu bar appears, that's the default iOS implementation of split view. But I locked the orientation to landscape only.
