### ISSUE TITLE
FGI_iOS-024 bug: n the Project Area, when a user deletes an item in that has been moved to a different category already, the app crashes.

### ISSUE THREAD

**Issue by anjgarong** [SiliconValleyInsight/fgi-catalog-ios#17]
Screen: Project Area

Steps to Replicate:
• open the app
• search Febo (CHAIRS category)
• tap the first item in the result
• add to project
• search Pathos (TABLES category)
• tap the first item in the result
• add to project (2 inventories)
• go to Project Area
• tap Edit
• move Febo to the TABLES category
• delete Febo
app crashes

Expected Behavior:
The item, even though it has been moved to another category, must be removed from the list when the user taps Delete (just like how it is done when an item is under its original category).

**Comment by vinogradnaya** [comment]
fixed build 1.17
