### ISSUE TITLE
FGI_iOS-020 enhancement: When a user views the items in the Project Area, load the thumbnails that they have chosen for each item. 

### ISSUE THREAD

**Issue by anjgarong** [SiliconValleyInsight/fgi-catalog-ios#18]
Screen: Project Area

Steps to Replicate:
• open the app
• choose any product
• choose a different thumbnail for that product (any thumbnail except the default)
• add that item to the Project Area
• go to the Project Area
notice that the thumbnail loaded for that project is the default thumbnail and not the chosen thumbnail

Expected Behavior:
The user will see the chosen thumbnail of the item he/she added to the project, not just in the email/print, but also in the Project Area screen of the app. This is to avoid confusion.

**Comment by vinogradnaya** [comment]
Fixed in build 1.17
