### ISSUE TITLE
FGI_iOS-022 bug: In the Project Area, when a user moves an item to a different category, that item is not recognized as “added to project” already.

### ISSUE THREAD

**Issue by anjgarong** [SiliconValleyInsight/fgi-catalog-ios#19]
Screen: Project Area and Product

Steps to Replicate:
• open the app

• search Febo (CHAIRS category)
• tap the first item in the result
• add to project

• search Pathos (TABLES category)
• tap the first item in the result
• add to project (2 inventories)

• go to Project Area
• tap Febo
notice there is a check mark under Project Area column in the Stocking Information table (EXPECTED)
• go back
• tap Edit
• move Febo to the TABLES category
• tap Done
• tap Febo
notice there is NO check mark under Project Area column in the Stocking Information table (NOT EXPECTED. stay on this screen to continue testing later)

Note: this causes a lot of bugs like having duplicate items in the Project Area, which should not happen

proceed to this:
• add the item to the project (put a check mark)

• go to Project Area
notice that there are already 2 Febo items. one under TABLES and one under CHAIRS (NOT EXPECTED. NOT ALLOWED.)

Expected Behavior:
When an item is added to a project, even though it is moved to a different category, once you tap it to see its Product page, there should be a check mark, still.

**Comment by vinogradnaya** [comment]
fixed in build 1.17
