### ISSUE TITLE
Build-specific change: text modifications

### ISSUE THREAD

**Issue by anjgarong** [SiliconValleyInsight/fgi-catalog-ios#20]
For the B&B Italia build, please modify the following:

"Categories" to "Typologies"
Where: Menu on the side

"Project Area" to "Cart"
Where: Menu on the side

"Untitled Project" to "Untitled Cart"
Where: Project Area screen

"See Project Notes" to "See Notes"
Where: Project Area screen

"Project Notes" to "Cart Notes"
Where: Project Notes Popup

**Comment by vinogradnaya** [comment]
Fixed in build 1.17

**Comment by anjgarong** [comment]
The Cart Page is still referred to as "Project Area" in the navigation bar.

Steps to Check:
• open the app
• go to Cart (make sure there are items in the cart)
• tap an item (a product)
Notice that on the navigation bar at the tap, it is still "Project Area".

![11100002_10206648448880602_1557476994_n](https://cloud.githubusercontent.com/assets/2359553/7246651/e9bc6cb4-e832-11e4-93d6-24cefb672f62.jpg)

**Comment by vinogradnaya** [comment]
fixed in build 1.21

**Comment by anjgarong** [comment]
Sorry that I also forgot to include this one. Please change "Project Area" to "Cart".

Screen: Product (Stocking Information table)

Steps to Check:
• open the app
• go to a specific Product
Notice that the rightmost column of the Stocking Information table is still "Project Area".

**Comment by vinogradnaya** [comment]
fixed in build 1.26
