### ISSUE TITLE
FGI_iOS-014 related bug: Anj: When there is no information from the QR code, there is a prompt "Unable to get information" but the scanning does not resume to normal.

### ISSUE THREAD

**Issue by anjgarong** [SiliconValleyInsight/fgi-catalog-ios#21]
Screen: Scan

Steps to Replicate:
• open the app
• go to Scan
• scan any QR code that is not an official B&B QR code
notice that there will be a prompt "Unable to get information" but after that, the scanning won't resume back to normal

![svi wrong qr code screenshot](https://cloud.githubusercontent.com/assets/2359553/7246599/2b8bbaf6-e832-11e4-849a-41e5b56ccdd6.jpg)

**Comment by vinogradnaya** [comment]
fixed in build 1.21
