### ISSUE TITLE
Keyboard layout change: In the Cart page, when editing the name of a category/topology (section header), the keyboard must show "Done" instead of "return".

### ISSUE THREAD

**Issue by anjgarong** [SiliconValleyInsight/fgi-catalog-ios#23]
Screen: Cart

Steps to Replicate:
• open the app
• go to Cart (make sure that there are items in the cart)
• tap a section header

Notice that the keyboard layout shows "return". Please change it to "Done".

![img_5042](https://cloud.githubusercontent.com/assets/2359553/7345386/ab1bf172-ed06-11e4-9a2e-7fdf84b5772d.PNG)

**Comment by vinogradnaya** [comment]
fixed in build 1.26
