### ISSUE TITLE
Quantity column does not show the quantity of the item.

### ISSUE THREAD

**Issue by anjgarong** [SiliconValleyInsight/fgi-catalog-ios#24]
Screen: Product

To check, just go to the Product page and notice that the Quantity column of the Stocking Information table does not show the quantity.

Reference Screenshot:
![image](https://cloud.githubusercontent.com/assets/2359553/7346946/fc8ceb10-ed15-11e4-944c-5162971cd39a.jpg)

Screenshot of Product Stocking Information API result:
![image](https://cloud.githubusercontent.com/assets/2359553/7346955/1b56bfb2-ed16-11e4-9e1f-d693e8599b0b.jpg)

**Comment by vinogradnaya** [comment]
fixed in build 1.26
