### ISSUE TITLE
quotations generated from mobile app doesn't send web logs

### ISSUE THREAD

**Issue by anjgarong** [SiliconValleyInsight/fgi-catalog-ios#33]
if a user emails a quotation from the mobile app, there's no additional log

Stef and I checked the quotation API and it seems to work fine

Steps to Check:
go to http://bebitaliamanila.com/api/quotations/
posting something from there
login to bebitaliamanila.com/admin
go to quotations
notice that's there is an additional log

Steps to check on mobile: 
from cart page, email out quotation 
email is sent/received, but no log in app

**Comment by vinogradnaya** [comment]
fixed, I tested on the admin site - the quotations are logged

**Comment by anjgarong** [comment]
fixed
