### ISSUE TITLE
Icons on bottom bar

### ISSUE THREAD

**Issue by stefsy** [SiliconValleyInsight/fgi-catalog-ios#34]
Icons for Cart, Search, Products. @vinogradnaya what kind of assets (dimensions, specs) do you need? 

@anjgarong will make them! or copy them from somewhere first as placeholder icons.

**Comment by vinogradnaya** [comment]
Needed sizes:
@2x : about 50 x 50 (max: 96 x 64)
@3x : about 75 x 75 (max: 144 x 96)

**Comment by anjgarong** [comment]
done and implemented

**Comment by anjgarong** [comment]
@vinogradnaya please change the scan icon to the new scan icons in this folder: https://goo.gl/c1pzxK

**Comment by stefsy** [comment]
Those look much better :)
