### ISSUE TITLE
Allow users to choose a picture among the thumbnails, to be shown in the quotation

### ISSUE THREAD

**Issue by anjgarong** [SiliconValleyInsight/fgi-catalog-ios#5]

**Comment by stefsy** [comment]
In the product screen, when user taps one of the thumbnails, please show thumbnail as the biggest image, and use that thumbnail in the quotation HTML email.

**Comment by vinogradnaya** [comment]
@stefsy 
Imagine a user selected several inventories. How many thumbnails a user may select?
1) case: only one. The selected thumbnail will apply to all of the chosen inventories? 
2) case: multiple. How should I bind selected inventory and selected thumbnail?

**Comment by stefsy** [comment]
@vinogradnaya 

User may select 1 image per product, regardless of the # of inventories of that product they have added to the project area. 

The image can be selected from the 5 thumbnails + the 1 main image. 

For now, let's apply the same image to all the chosen inventories. So if the user adds 1 Leukon chair that costs 14,000, and another 1 Leukon chair that costs 20,000, the image thumbnail for both those chairs will be the same.

**Comment by vinogradnaya** [comment]
@stefsy Ok, thanks! If selected thumbnail is shown on place of the big image, then the image that was big should be shown on place of thumbnail? So that user could select it later?

**Comment by stefsy** [comment]
@vinogradnaya exactly!
