### ISSUE TITLE
Full product code search

### ISSUE THREAD

**Issue by anjgarong** [SiliconValleyInsight/fgi-catalog-ios#7]

**Comment by stefsy** [comment]
@ray-dino Additional API endpoint to allow search by Product Code, not just search by Name. 

After, @vinogradnaya to implement in iOS

**Comment by vinogradnaya** [comment]
@stefsy shall we add some switch to the app to know if user inputs a name or product code?

**Comment by ray-dino** [comment]
We have an API endpoint to show the details of a single product using item code: `/api/products/<item code>/`. Are you saying you want to search for partial matches to item code?

@vinogradnaya @stefsy

**Comment by stefsy** [comment]
@vinogradnaya  no need to add switch for name vs. product code

@ray-dino my bad, I blanked out on the search by full product code part of the API. This feature is much simpler than it looked at first. For MVP all that needs to be done is for Kate to add the option for user to search via full product code along with search via full product name.

Partial match can follow later as an additional feature if clients wants it.

**Comment by vinogradnaya** [comment]
@stefsy "all that needs to be done is for Kate to add the option for user to search via full product code along with search via full product name".

How should I assume what a user typed in - a name or product code? Should I first call API "search by name" and if it fails call "search by code"?

**Comment by ray-dino** [comment]
Got it. The API endpoint will be `/api/products/?code=`. It'll be ready today on the next deployment.

**Comment by stefsy** [comment]
Either way is fine with me. @vinogradnaya please comment and decide.

**Comment by ray-dino** [comment]
I just added both. They don't interfere with each other. Just to recap, here are the available url parameters:

`name`: case-insensitive exact string match to product name. 
`?name=FEBO` matches `{item_code: 2808V, item_name: "Febo"}`

`code`: case-insensitive exact string match to product code. 
`?code=acan4` matches `{item_code: "ACAN4", item_name: "Mida"}`

`search`: case-insensitive partial string match to product code or product name.
`?search=abc`matches
```
[
{item_code: "12ABC3",  item_name="Evette Settee"},
{item_code: "XYZ", item_name="ABC chair"}
]
```

https://github.com/SiliconValleyInsight/fgi-catalog-web/pull/32
This is ready on the next deploy.

**Comment by vinogradnaya** [comment]
@ray-dino thanks! that's exactly what I needed!

**Comment by vinogradnaya** [comment]
@ray-dino Please take a look: http://fgi.marksteve.com/api/products/?search=Leukon returns non-relative items, i.e. Pathos, Febo etc.

**Comment by ray-dino** [comment]
@vinogradnaya I'm sorry, I can't replicate the error.  `http://fgi.marksteve.com/api/products/?search=Leukon` seems to return only the 8 Leukon products.

**Comment by vinogradnaya** [comment]
@ray-dino so strange. Today it does work as expected, but yesterday I got all DB in the response. It's good it works now, thank you!
