### ISSUE TITLE
Add Terms and Conditions to the quotation (email/print)

### ISSUE THREAD

**Issue by anjgarong** [SiliconValleyInsight/fgi-catalog-ios#8]
- still waiting for the Terms and Conditions from FGI

**Comment by stefsy** [comment]
This is an unofficial quotation. Item stock may change and prices are subject to change. Formal quotation to follow. 


*STOCK ITEMS*			
					
	Items shall only be delivered upon full payment and clearing of checks		
		
Maximum one (1) month free storage		
	
Items will be held for five (5) days upon reservation and will automatically be released if no confirmation is 
made within the period
		
No reservation is accepted during sale events		
									
*INDENT ORDERS*						
	50% down payment upon placement of order		
		60-day Post Dated Check for the 50% balance is required		
	Delivery approximately five (5) to eight (8) months from date of payment		
		Items shall only be delivered upon full payment and clearing of checks		
		Maximum one (1) month free storage upon arrival		
									

*All sales are final.*
We offer free delivery within Metro Manila and corresponding charges apply for delivery outside Metro Manila.
A storage fee of P 950.00 per item per month shall be charged to the client exceeding the one (1) month free storage period
Maximum allowable storage duration is one (1) year from agreed delivery date .
Prices are subject to change unless full cash/check payments have been made.

**Comment by vinogradnaya** [comment]
fixed in build 1.11
